services:
  cpp_app:
    build:
      context: .
      dockerfile: Dockerfile.cpp
    volumes:
      - cpp:/app/cpp
    command: ["./daemon", "1", "2"]  # Exemple de commande avec des arguments

  flask_app:
    build:
      context: ./flask
      dockerfile: Dockerfile.flask
    ports:
      - "8050:8050"
    env_file:
      - flask/.env
    volumes:
      - cpp:/app/cpp
      - ./flask:/app
      # - ./flask/src:/app/src
    depends_on:
      - cpp_app
    # command: ["ls", "-l","-a"]
    command: ["/bin/bash", "run.sh"]

volumes:
  cpp:
