FROM arm64v8/python:latest
WORKDIR /app

# Copier les dépendances Python
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le fichier .env
COPY .env .env
RUN [ ! -f .env ] || export $(grep -v '^#' .env | xargs)

# Copier le script de démarrage
COPY run.sh .

# Copier le code source de l'application Flask
COPY . .

# Définir la commande par défaut
CMD ["/bin/bash", "run.sh"]
